# Script sourced by LightDM

# Not placed in zshenv because doesn't get sourced before this file
#export RXVT_SOCKET="$HOME/.cache/urxvtd-socket"
# Urxvt daemon
#urxvtd -q &

# $HOME/.xsession-errors is hard coded in LightDM
# Link .xsession-errors in log folder
#if [ ! -L $HOME/.xsession-errors ]; then
#	ln -sf /var/log/.xsession-errors $HOME/.xsession-errors
#fi

# Remove .xsession-errors.old, generated by LightDM
#if [ -f $HOME/.xsession-errors.old ]; then
#	rm $HOME/.xsession-errors.old
#fi

