# Script sourced by LightDM

# Map super keys
exec /usr/bin/xmodmap $HOME/.config/xmodmaprc/change_super_key &

# URXVT config file
exec /usr/bin/xrdb $HOME/.config/urxvt/Xresources &

# Urxvt daemon condif and execution
# Not placed in zshenv because doesn't get sourced before this file
export RXVT_SOCKET="$HOME/.cache/urxvt/urxvtd-socket"
urxvtd -q &

# Clipboard daemon
clipster -d &

# $HOME/.xsession-errors is hard coded in LightDM
# Link .xsession-errors in log folder
if [ ! -L $HOME/.xsession-errors ]; then
	ln -sf /var/log/.xsession-errors $HOME/.xsession-errors
fi
# Remove .xsession-errors.old, generated by LightDM
if [ -f $HOME/.xsession-errors.old ]; then
	rm $HOME/.xsession-errors.old
fi

# Set keyboard layout
xkbcomp -I$HOME/.config/xkb ~/.config/xkb/map $DISPLAY

