# Sourced by i3

# URXVT config file
#exec /usr/bin/xrdb /home/marco/.config/urxvt/Xresources &
# Map super keys
#exec /usr/bin/xmodmap /home/marco/.config/xmodmaprc/change_super_key &
# Urxvt daemon
#urxvtd -q &
# Clipboard daemon
#clipster -d &

# $HOME/.xsession-errors is hard coded in LightDM
# Link .xsession-errors in log folder
#if [ ! -L $HOME/.xsession-errors ]; then
#	ln -sf /var/log/.xsession-errors $HOME/.xsession-errors
#fi

# Remove .xsession-errors.old, generated by LightDM
#if [ -f $HOME/.xsession-errors.old ]; then
#	rm $HOME/.xsession-errors.old
#fi

# Path is sourced also in .zshenv
PATH="/home/marco/scripts:$PATH"

