#! /bin/sh

killall -q polybar
killall -q sxhkd
killall -q picom
killall -q udiskie

# Need testing
# xrdb -merge $HOME/.Xresources

get_external_monitor=$(xrandr --query | grep -w 'DP-1')
if [[ $get_external_monitor = *disconnected* ]]; then
    echo "1 monitor"
    bspc monitor -d 1 2 3 4 5 6 7 8 9 10
else
    echo "2 monitors"
    xrandr --output DP-1 --auto --right-of eDP-1
    bspc monitor eDP-1 -d 1 2 3 4 5
    bspc monitor DP-1 -d 6 7 8 9 10
    polybar bar2 >> /tmp/polybar2.log 2>&1 &
fi

polybar bar1 >> /tmp/polybar1.log 2>&1 &

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

exec sxhkd &

# exec urxvr &
# polybar example &

# Keyboard
setxkbmap -layout us,it
setxkbmap -option 'grp:alt_shift_toggle'

# Set caps lock to hyper key
xmodmap /home/marco/.config/xmodmaprc/change_super_key

# Set wallpaper
feh --no-fehbg --bg-scale '/home/marco/Documents/wallpaper.jpeg'

# Compositor
picom -b

# USB mounter
udiskie &

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
