#!/bin/bash

# Unlock if bluetooth card is locked (password requested)
if [[ $(rfkill -r | grep 'bluetooth hci0 blocked') = *bluetooth\ hci0\ blocked* ]]; then
  sudo rfkill unblock bluetooth
  echo "sudo rfkill unblock bluetooth"
fi

# Disable bluetooth card if powerd on
if [[ $(bluetoothctl show | grep 'Powered: yes') = *Powered:\ yes* ]]; then
  bluetoothctl power off
  echo "bluetoothctl power off"
else
  echo "Already off"
fi
