#!/bin/bash

MAC=CD:9F:B9:BD:FA:FE

# Unlock if bluetooth card is locked (password requested)
if [[ $(rfkill -r | grep 'bluetooth hci0 blocked') = *bluetooth\ hci0\ blocked* ]]; then
  echo "Card was blocked, unblocking card"
  sudo rfkill unblock bluetooth
fi

# Check if bluetooth service is running
if ! systemctl is-active --quiet bluetooth ; then
  echo "Bluetooth service is off, enabling"
  sudo systemctl enable bluetooth
  sudo systemctl start bluetooth
fi

# Enable bluetooth card if powerd off
if [[ $(bluetoothctl show | grep 'Powered: no') = *Powered:\ no* ]]; then
  echo "Powering on card"
  bluetoothctl power on
else
  if [[ "$(bluetoothctl show | grep 'Powered: yes')" = *Powered:\ yes ]]; then
    echo "Card was on, connecting to device"
    # Connect to mouse
    bluetoothctl connect $MAC
  fi
fi


# IMPORTED FROM bluetooth_power_off

# Unlock if bluetooth card is locked (password requested)
# if [[ $(rfkill -r | grep 'bluetooth hci0 blocked') = *bluetooth\ hci0\ blocked* ]]; then
#   sudo rfkill unblock bluetooth
#   echo "sudo rfkill unblock bluetooth"
# fi

# # Disable bluetooth card if powerd on
# if [[ $(bluetoothctl show | grep 'Powered: yes') = *Powered:\ yes* ]]; then
#   bluetoothctl power off
#   echo "bluetoothctl power off"
# else
#   echo "Already off"
# fi
