#!/bin/bash

# Unlock if bluetooth card is locked (password requested)
if [[ $(rfkill -r | grep 'bluetooth hci0 blocked') = *bluetooth\ hci0\ blocked* ]]; then
  sudo rfkill unblock bluetooth
  echo "sudo rfkill unblock bluetooth"
fi

# Enable bluetooth card if powerd off
if [[ $(bluetoothctl show | grep 'Powered: no') = *Powered:\ no* ]]; then
  bluetoothctl power on
  echo "bluetoothctl power on"
else
  echo "Already on"
fi
