#!/bin/bash
# Count words from clipboard
WORDS=$(xclip -o -selection clipboard | wc -w)
CHARS=$(xclip -o -selection clipboard | wc -c)

notify-send -t 3000 -a "Count words" "Count" "$WORDS words\n$CHARS chars"
