#!/bin/bash

# Delete commands from zsh history file and put them in a temporary file
# Example: 'delete-command ls -l'
# Will delete all command(s) matching exactly the arguments
#
# Example 'delete-command -a ls -l'
# Will delete all command(s) matching the substring, for example:
# - ls -l | wc -l
# - ls -la
# - echo ls -l

ROOT="/home/marco/.cache/zsh"
# Join commands arguments in one string
COMMAND_TO_DEL="$*"

# Check substring match
if [[ "$1" == "-a" ]]; then
  # Remove first 3 characters '-a '
  COMMAND_TO_DEL="${COMMAND_TO_DEL:3}"
fi

# Escape keyword for regex
ESCAPED_KEYWORD=$(printf '%s\n' "$COMMAND_TO_DEL" | sed -e 's/[]\/$*.^[]/\\&/g')
if [[ "$1" != "-a" ]]; then
  # Select exactly string
  REGEX=": [0-9]*:0;$ESCAPED_KEYWORD"
else
  REGEX="$ESCAPED_KEYWORD"
fi


# Save to temporary file
DEST_FILE="$ROOT/history-$(date +%y-%m-%d_%H:%M:%S.%3N)"
# ^ and $ are start and end of the file
grep -E "$REGEX" $ROOT/history > $DEST_FILE

# Delete lines from original file
sed --in-place "/$REGEX/d" $ROOT/history

echo "Deleted $(wc -l $DEST_FILE | awk '{print $1}') lines"
echo "Written in file '$DEST_FILE'"
