#!/usr/bin/env bash

# udev runs as root, so we need to tell it how to connect to the X server
export HOME="/home/marco"
export DISPLAY=:0
export XAUTHORITY=$HOME/.Xauthority

sleep 0.4

# Dispaly setup
xrandr --output eDP1 --mode 1920x1080
if xrandr | grep -q "\bDP1 connected\b"; then
	# External monitor connected
	xrandr --output DP1 --auto
	if grep -q "open" /proc/acpi/button/lid/LID/state; then
		# Lid open
		echo "Lid open"
		xrandr --output DP1 --right-of eDP1
	else
		# Lid closed
		echo "Lid closed"
		xrandr --output eDP1 --off
	fi
else
	# External monitor disconnected
	echo "External monitor disconnected"
	xrandr --output DP1 --off
fi

# On wake up sometimes dpi is not 100
xrandr --dpi 100

# Start polybar
killall polybar
/usr/bin/polybar --config=$HOME/.config/polybar/config bar1 &
/usr/bin/polybar --config=$HOME/.config/polybar/config bar2 &

# Set wallpaper
feh --no-fehbg --bg-scale "$HOME/Documents/wallpaper-gradient.png"
