#!/bin/bash
PSW=$(pwgen -s --numerals -1 16)
# Trim new line character
PSW="$(echo $PSW | tr -d '\n')"
# Current date
DATE="$(date +'%Y-%m-%d_%H-%M-%S')"
# Copy using gpaste
gpaste-client add-password ${DATE} ${PSW}
