#!/bin/bash
PSW=$(pwgen -s --numerals -1 16)
# Trim new line character
PSW="$(echo $PSW | tr -d '\n')"

# Remove newspace with echo -n
echo $PSW | xclip -selection clipboard

notify-send -t 3000 "Generate Password" "Copied to clipboard"
