#!/bin/bash

# Mount GoPro with simple-mtpfs checking if it's already mounted
# MOUNT_DIR set in ~/.zshenv

DEV_MOUNT_DIR="$MOUNT_DIR/GoProTMP"

if [[ $(simple-mtpfs -l) = *1:\ GoProHERO4* ]]; then
  if [[ ! -d "${DEV_MOUNT_DIR}" ]]; then
    echo "GoPro mounted"
    # Needs both read and write permissions (755 not working)
    sudo mkdir --mode=777 -p $DEV_MOUNT_DIR
    simple-mtpfs --device 1 $DEV_MOUNT_DIR
  else
    echo "GoPro already mounted"
  fi
  echo "DO NOW USE RANGER, just copy file with 'cp -rv GoPro ~/Downloads'"
else
  echo "GoPro device not connected"
fi
