#!/bin/bash
ROOT="/home/marco/.cache/zsh"
DATENOW="$(date +%y-%m-%d_%H:%M:%S.%3N)"

# Remove duplicate commands
cat -n "$ROOT/history" | sort -r | sort -t ';' -uk2 | sort -nk1 | cut -f2- > $ROOT/history-new
# Remove lines ending with \
sed --in-place '/.*\\$/d' $ROOT/history-new
# Remove lines longer than n characters
sed --in-place '/.\{135\}/d' $ROOT/history-new
# Rename oldest file to tmp
mv $ROOT/history $ROOT/history-$DATENOW
mv $ROOT/history-new $ROOT/history

# Move old files to tmp
CACHE_DEST=/tmp/zsh-cache
mkdir -p $CACHE_DEST
find $ROOT -name "history-*" -mtime +7 -exec mv -t $CACHE_DEST {} + 

echo "History file '/home/marco/.cache/zsh/history' cleaned"
