#!/bin/bash
# Run as root from: /etc/udev/rules.d/00-keyboard.rules

# Setup logger if root, otherwise print
if (( EUID == 0 )); then
    exec >> /var/log/keyboard.log 2>&1
fi

echo "=== Run: $(date '+%Y-%m-%d %H:%M:%S') ==="

export HOME="/home/marco"
export DISPLAY=":0.0"
export XAUTHORITY=$HOME/.Xauthority

# If display server is running, timeout set because the command takes time to fail
# https://stackoverflow.com/a/11965765/7924557
if timeout 0.1 xset q &>/dev/null; then
  echo "Running xkbcomp"
  notify-send -t 3000 -a "Keyboard Setup" "⏩ Running"
  # Sleep needed for xkbcomp, 0.5s for I3, 3s for KDE
  sleep 3
  xkbcomp -I$HOME/.config/xkb ~/.config/xkb/map $DISPLAY &> /dev/null

  # Switch off caps lock key if enabled
  if ! xset q | grep "Caps Lock:   off" > /dev/null; then
    echo "Running xdotools caps lock"
    xdotool key Caps_Lock
  fi

  # Switch off num lock key if enabled
  if ! xset q | grep "Num Lock:    off" > /dev/null; then
    echo "Running xdotools num lock"
    xdotool key Num_Lock
  fi

  #echo "Running scripts/logkeys-start"
  #/home/marco/scripts/logkeys-start
fi
echo "=== End ==="
notify-send -t 2000 -a "Keyboard Setup" "✔️ Done"

