#!/usr/bin/bash

exec_hook() {
  # --not-when-fullscreen removed because would not allow sleep also if fullscreen in another window
  xidlehook \
    --not-when-audio \
    --detect-sleep \
    --timer 540 'lock -b' 'lock -r' \
    --timer 60 'lock -l' 'lock -r'
}

exec_lock() {
  # xset used for screen saver respectively for 10 sec and infinity
  killall xidlehook
  brightness_reset
  xset s 20
  betterlockscreen -l &&
    xset s 0 &&
    exec_hook
}

brightness_reset() {
  xrandr --output DP1 --brightness 1
  xrandr --output eDP1 --brightness 1
}

while getopts 'hlsbr' flag; do
  case "${flag}" in

  # hook (-h)
  h)
    killall xidlehook
    exec_hook
    ;;

  # lock (-l)
  l)
    exec_lock
    ;;

  # sleep (-s)
  # Not using betterlockscreen -s because would not be possible to emulate the behaviour:
  # if was sleeping, waken up and then password was not inserted just sleep again because
  # on i3lock, xidlehook inserts text in the password field.
  s)
    systemctl suspend
    exec_lock
    ;;

  # brightness set (-b)
  b)
    brightness=1
    for i in {1..25}; do
      echo "Brightness ${brightness}"
      brightness=$(echo "$brightness - 0.02" | bc)
      xrandr --output DP1 --brightness $brightness
      xrandr --output eDP1 --brightness $brightness
    done
    ;;

  # brightness reset (-r)
  r)
    brightness_reset
    ;;
  esac
done
