#!/bin/bash

AMOUNT=80
WHAT=words
START=yes

while getopts ":n:s" opt; do
  case $opt in
    n)
      AMOUNT=$OPTARG
      ;;
    *)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done

curl -s -X POST https://www.lipsum.com/feed/json -d "amount=$AMOUNT" -d "what=$WHAT" -d"start=$START" | jq -r '.feed.lipsum' | tr '\n' ' ' | xclip -selection clipboard

notify-send -t 3000 "Lorem ipsum generator" "Copied $AMOUNT $WHAT to clipboard"

