#!/usr/bin/bash

# MOVED TO LOCK SCRIPT, left for testing, remove if unused

while getopts 'rs' flag; do
	case "${flag}" in
	s)
		# brightness=1
		# for i in {1..25}; do
		# 	# Not needed because xrandr takes a lot of times anyway
		# 	# sleep 0.03
		# 	echo "Brightness ${brightness}"
		# 	brightness=$(echo "$brightness - 0.02" | bc)
		# 	xrandr --output DP1 --brightness $brightness
		# 	xrandr --output eDP1 --brightness $brightness
		# done
		;;
	r)
		# xrandr --output DP1 --brightness 1
		# xrandr --output eDP1 --brightness 1
		;;
	esac
done
