#!/bin/bash

pic_name="/home/marco/Pictures/screenshot_$(date +"%Y-%m-%d")_$(date +"%H-%M-%S").png"

# Get window (-w) selection (-s)
while getopts 'ws' flag; do
  case "${flag}" in
  w)
    gnome-screenshot --window --file=$pic_name
    ;;
  s)
    gnome-screenshot --area --file=$pic_name --delay=1
    ;;
  esac
done

# Copy to clipboard
#gpaste-client file $pic_name
xclip -selection clipboard -t image/png -i $pic_name

notify-send -t 3000 "Screenshot" "Copied to clipboard"

