#!/usr/bin/bash
# Run in current shell instead of sub-shell with "source source-env"
# 'se' set in .zshrc

function source_file () {
	if [ -f $1 ]; then
		source $1
		echo "✅ $2"
	else
		echo "❌ $2"
	fi
}

source_file ".venv/bin/activate" "virtual env"
source_file ".envvars" "env vars"

