#!/bin/bash
pic_name="/home/marco/Pictures/screenshot_$(date +"%Y-%m-%d")_$(date +"%H-%M-%S").png"
spectacle --background --copy-image --region --nonotify --output=$pic_name
txt_file="/tmp/tesseract-ocr"
tesseract $pic_name $txt_file
xclip -selection clipboard < $txt_file
notify-send -t 3000 "Tesseract - OCR" "Copied to clipboard"
