#!/bin/bash

pamixer --unmute

# Get increase (-i) decrease (-d) mute (-m)
while getopts 'idm' flag
do
  case "${flag}" in
    i)
        pamixer -i 2
    ;;
    d)
        pamixer -d 2
    ;;
    m)
        pamixer --set-volume 0
    ;;
  esac
done
