#!/bin/bash

pamixer --unmute

# Get increase (-i) decrease (-d) mute (-m)
while getopts 'gidm' flag; do
  case "${flag}" in
  g)
    echo "$(pamixer --get-volume)%"
    ;;
  i)
    pamixer -i 2
    ;;
  d)
    pamixer -d 2
    ;;
  m)
    pamixer --set-volume 0
    ;;
  esac
done
