#!/bin/bash

# Add something to the string, if not would have been impossible to
# commit the script that avoid committing jajajajajaja
MESSAGE="no${NOTHING}commit"
if git commit -v --dry-run | grep -i $MESSAGE >/dev/null 2>&1 ; then
  echo "Trying to commit non-committable code."
  echo "Remove the ${MESSAGE} string and try again."
  exit 1
fi

# Run local commit hooks
if [ -e ./.git/hooks/pre-commit ]; then
  ./.git/hooks/pre-commit "$@"
fi
